### ISSUE TITLE
Issue swapping to Github dark theme in Material Theme Lite on IntellijIDEA 2020.3

### ISSUE THREAD

**Issue by NicolaM94** [mallowigi/material-theme-ui-lite#25] opened 2021-01-18 14:03 UTC
Reporting the previous thread from IntelliJIDEA reddit page, as I first thought it was an IDE bug.
As the title says, I've been running into some issues while swapping to github dark from material theme lite plugin in IntellijIDEA 2020.3.
I'm currently working on Manjaro with a snap installation.
The swap action completely broke the UI, so menus and and left panel menus aren't accessible, as for the project tree, you can see icons in the top right side dragged multiple times one on another and the editor is completely unusable. Plus the IDE becomes totally unresponsive and buggy (still closable though).

![intellij](https://user-images.githubusercontent.com/51529905/104924788-3727eb80-599e-11eb-9d01-0d9239662959.png)

I had no backup of my IDE settings, and I've been unable to revert the settings manually from IDE settings folder, but I managed to start a working instance of the IDE by manually removing the theme .jar file in the installation folder:

`cd /home/.local/share/JetBrains/IdeaIC2020.3/Material\ Theme\ UI\ Lite/lib/`
`rm material-theme-lite-12.jar`

After that, the IDE started with no problem, with the darcula theme and the light theme colors in the editor.

**Comment by mallowigi** [comment] 2021-01-18 14:09
looks like a duplicate of https://github.com/mallowigi/material-theme-ui-lite/issues/24 no ?

**Comment by NicolaM94** [comment] 2021-01-18 14:14
Whoops, sorry, didn't see the previous one. I was ask to report from reddit and I reposted without looking. Sorry for that again!

**Closed** 2021-01-18 14:17 UTC

**Comment by mallowigi** [comment] 2021-01-18 14:58
fixed, submitting update

**Comment by NicolaM94** [comment] 2021-01-18 15:18
Awesome! Thank you so much!
