### ISSUE TITLE
Color Scheme Console Font not persisting

### ISSUE THREAD

**Issue by necampanini** [mallowigi/material-theme-ui-lite#51] opened 2021-06-24 01:27 UTC
In switching material themes, the console font always resets back to the plugin default, rather than the overall editor font, or even the color scheme specific console font override.

Version of plugin: 15.1

Image attached: switched to Dracula with the Color Scheme console font override already saved from previous edits, but console font falls back to plugin default which is too small for personal preference.

![image](https://user-images.githubusercontent.com/3249164/123188190-9b793a80-d469-11eb-8d71-e2a90dd34c3e.png)

**Comment by mallowigi** [comment] 2022-04-23 16:36
Duplicate of https://github.com/mallowigi/material-theme-issues/issues/59

**Closed by mallowigi** 2022-04-23 16:36 UTC
