### ISSUE TITLE
CSS color preview broken in some themes

### ISSUE THREAD

**Issue by Emonadeo** [mallowigi/material-theme-ui-lite#11] opened 2020-02-05 21:38 UTC
### Expected behavior

![image](https://user-images.githubusercontent.com/13782948/73883796-da9eef80-4864-11ea-99d1-97decf804538.png)
_Darcula_

### Actual behavior

![image](https://user-images.githubusercontent.com/13782948/73883563-754afe80-4864-11ea-927e-c8c5b6710375.png)
_Material Darker_

### Steps to reproduce (if needed)

> The problem seen in the picture above occurs for any selected Material Theme, as well as any standalone Editor Material Color Scheme in combination with a JetBrains official UI theme like Darcula.

1. Go to _Settings `->` Editor `->` General `->` Appearance_
2. Enable _Show CSS color preview as background_
3. Create a CSS file and set any color property

(The same issue with the text being gray occurs when enabling Color Preview in the Gutter Icons and using Sass/SCSS variables.)

### Environment

**WebStorm 2019.3.2**
**OS:** Linux 5.4.15-2-MANJARO
**Build:** #WS-193.6015.40, built on January 21, 2020
**Runtime version:** 11.0.5+10-b520.30 amd64
**Plugin version:**  8.0 _(The problem also occurs in Material Theme UI 4.11.5)_
**Enabled Plugins:** .ignore, Atom Material Icons, Material Theme UI Lite, Rainbow Brackets

**Comment by mallowigi** [comment] 2021-05-12 08:37
Can't reproduce anymore, closing.

**Closed by mallowigi** 2021-05-12 08:37 UTC
